### ISSUE TITLE
Service implementor cannot extend multiple ThriftServices interfaces.

### ISSUE THREAD

**Issue by aching** [facebook/swift#170]
I have a class that implements two different interfaces that are both annotated as ThriftService objects.  When passing an instance of this class to ThriftServiceProcessor, it will fail due to implementing multiple services.  This is useful functionality, per se, to limit clients from having access to all the methods.  Can we simply remove the check here?

Caused by: java.lang.IllegalStateException: service JobStatsStore extends multiple services
        at com.google.common.base.Preconditions.checkState(Preconditions.java:150)
        at com.facebook.swift.service.metadata.ThriftServiceMetadata.<init>(ThriftServiceMetadata.java:87)
        at com.facebook.swift.service.ThriftServiceProcessor.<init>(ThriftServiceProcessor.java:75)
        at com.facebook.swift.service.ThriftServiceProcessor.<init>(ThriftServiceProcessor.java:63)

**Comment by vicmosin** [comment]
Is there any way to extend generic interfaces?
```
@ThriftService
public interface BaseService<T> {

	@ThriftMethod
	T save(T object);
}
```

This one fails for example...

**Comment by dain** [comment]
To encode and decode in Thrift, we need to know the concrete type.  IIRC Swift will walk the type hierarchy to resolve the base type, but it must resolve to a concrete type, which this example does not.

**Comment by vicmosin** [comment]
Do you mean in generally? Or only regarding my example?
Take a look at my question:
http://stackoverflow.com/questions/30760377/use-generics-with-thriftservice

**Comment by andrewcox** [comment]
We don't support generic parameters on a service definition.
