### ISSUE TITLE
Stable UnresolvedAddressException on particular method

### ISSUE THREAD

**Issue by vicmosin** [facebook/swift#331]
I have very weird behavior in once of service implementations use swift.. The call stable fails with 

```
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101) ~[na:1.8.0_92-internal]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[na:1.8.0_92-internal]
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108) [netty-3.10.5.Final.jar!/:na]
```

but previous methods work fine, the server side also has no mention of error in this case. No load-balancer or so at environment.
What it can be?

**Comment by SergeyMakarenko** [comment]
Hi,
How could I reproduce this?
Thanks

**Comment by dain** [comment]
The `sun.nio.ch.SocketChannelImpl.connect` is simply validating the `InetAddress` by calling `java.net.InetSocketAddress#isUnresolved`, and it is reporting that the name could not be resolved to an address. I would guess this was caused by a DNS or network hiccup.
